### ISSUE TITLE
Background and Base Text Color Do Not Change

### ISSUE THREAD

**Issue by TylerMills** [benmarten/Monokai_Fish_OSX#1]
Using the latest version of Fish and OS X. Installing the theme changes syntax but doesn't change the background or text color. Not sure if this is expected behavior.

**Comment by benmarten** [comment]
Yes, you need to also install and select the Terminal Theme, did you do that? https://github.com/benmarten/Monokai_Fish_OSX/blob/master/Monokai.terminal
I think the fish shell itself cannot change the behavior of the OS X Terminal app... 

<img width="590" alt="screen shot 2016-03-14 at 8 59 31 pm" src="https://cloud.githubusercontent.com/assets/5960238/13767461/c658f9b6-ea27-11e5-9faf-37923947bc83.png">
