### ISSUE TITLE
color doesn't work

### ISSUE THREAD

**Issue by monajalal** [benmarten/Monokai_Fish_OSX#2]
Hey, any idea why the color doesn't work?
<img width="1177" alt="screen shot 2017-09-17 at 1 31 55 am" src="https://user-images.githubusercontent.com/1892917/30518301-07e45736-9b48-11e7-82f7-cbe69f1ddc54.png">

**Comment by krahlos** [comment]
Same problem here. Using macOS Sierra on MacBook Pro Late 2015. Any suggestions how to solve this issue?

**Comment by XRadevFRT** [comment]
Same! 😔

**Comment by ysze** [comment]
Same here. Would love to know how to fix it, thanks!

**Comment by benmarten** [comment]
I just tested it again. It works for me. I remove it completely and then installed it.
Did you follow the instructions? https://github.com/benmarten/Monokai_Fish_OSX#installation
What macOS, Terminal and Fish versions are you using?
Mine are 10.13.1, 2.8(400), 2.6.0.

**Comment by ysze** [comment]
Hi Ben, thanks for the reply. The colors work when I'm using vim, but the bash commands do not have color like the image you showed there. Thanks.

**Comment by fjsj** [comment]
Colors are working for me. Don't forget `fish set_colors.fish`
OSX 10.11.6 (15G18013)
Terminal Version 2.6.1 (361.1)
fish, version 2.7.0

**Comment by benmarten** [comment]
@ysze this does not currently work in bash, only fish.
